#!/usr/bin/with-contenv bash
# # This script sets up the status app

# Copy site files to /config
echo "Copying latest site files to config"
cp -rfT /site/ /config/www/

# Check for DB
if [ ! -f /config/status.db ]; then
    echo "Database file not found! Creating empty database"
    touch /config/status.db
else
    echo "Database file exists"
    chown abc:abc /config/status.db
fi

# Check for .env
if [ ! -f /config/www/.env ]; then
    echo "Env file not found! Creating .env file"
    cp /site/.env.example /config/www/.env
else
    echo "Env file exists"
fi

sed "s,DB_CONNECTION=.*,DB_CONNECTION=sqlite," -i.bak /config/www/.env
sed "s,DB_DATABASE=.*,DB_DATABASE=/config/status.db," -i.bak /config/www/.env

echo "Running database migrations"
php /config/www/artisan migrate

# Check app key exists
if grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /config/www/.env > /dev/null; then
    echo "App key exists"
else
    echo "Generating app key"
    php /config/www/artisan key:generate
fi

mkdir -p /config/log/status

cp /defaults/crontab /etc/crontabs/root

chown -R abc:abc /config
chmod u+s /bin/ping
